version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - library_network

  app:
    build: .
    container_name: library_app
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=library_management
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
    - .:/usr/src/app
    entrypoint: ["sh", "-c", "chmod +x /usr/src/app/init-script.sh && /usr/src/app/init-script.sh"]
    networks:
      - library_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - library_network
  
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - library_network

networks:
  library_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
